### ISSUE TITLE
Use container IP address instead of hard-coded IP [MongoDB]

### ISSUE THREAD

**Issue by dminca** [dminca/nomon#1]
in `./routes/index.js`

``` js
  var url = 'mongodb://172.17.0.5:27017/nomon';
```

Use `$CONTAINER_IP` instead of that hard-coded IP Address...

**Comment by goggenb** [comment]
Opened pull request for this in #5

**Comment by dminca** [comment]
Now I just realized I wasn't that specific. I was referring to the container **hostname**, but you got me :grin:

**Comment by dminca** [comment]
Closed by #5
